# Generated by Django 2.2.2 on 2019-06-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_image',
        ),
    ]
